CC = gcc
CFLAGS = -std='c99' -g -Wall

TARGET = lpfg

all: $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET).exe $(TARGET).c -lm

.PHONY : clean 
clean:

#rm -f $(TARGET).exe
	del $(TARGET).exe

